### ISSUE TITLE
Aspect Generators report from VanillaFix, command bug and Thaumonomicon entries

### ISSUE THREAD

**Issue by LupusParsec** [Rumaruka/IndustrialMagic-TechReborn-Crossover#2]
1. When any of the Aspect Generators are placed, VanillaFix returns an error. Looks like this happens because they are suposed to be able to face the four directors, but this don't happen for some reason. Also, I can be wrong, but I think there's one time I tryed to jump on them when placing them down and the world just crashed. More details in the following report:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

---- Minecraft Crash Report ----
// Why did you do that?

Time: 2022-08-24 02:56:37 BRT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=trm:aurgenerator, properties=[]}
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockStateContainer{block=trm:aurgenerator, properties=[]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.getValue(BlockStateContainer.java:201)
    at com.rumaruka.trm.common.blocks.generator.BlockAuramGenerator.setDefaultFacing(BlockAuramGenerator.java:41)
    at com.rumaruka.trm.common.blocks.generator.BlockAuramGenerator.onBlockAdded(BlockAuramGenerator.java:31)
    at net.minecraft.world.chunk.Chunk.setBlockState(Chunk.java:614)
    at net.minecraft.world.World.setBlockState(World.java:343)
    at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:180)
    at net.minecraft.item.ItemBlock.onItemUse(ItemBlock.java:54)
    at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:889)
    at net.minecraft.item.ItemStack.onItemUse(ItemStack.java:186)
    at net.minecraft.server.management.PlayerInteractionManager.processRightClickBlock(PlayerInteractionManager.java:481)
    at net.minecraft.network.NetHandlerPlayServer.processTryUseItemOnBlock(NetHandlerPlayServer.java:741)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:55)
    at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.processPacket(SourceFile:11)
    at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(SourceFile:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_321, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 584540592 bytes (557 MB) / 1073741824 bytes (1024 MB) up to 1073741824 bytes (1024 MB)
  JVM Flags: 8 total; -Xmx1024M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 11 mods loaded, 11 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                | Version      | Source                                          | Signature                                |
       |:------ |:----------------- |:------------ |:----------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft         | 1.12.2       | minecraft.jar                                   | None                                     |
       | LCHIJA | mcp               | 9.42         | minecraft.jar                                   | None                                     |
       | LCHIJA | FML               | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge             | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | baubles           | 1.5.2        | Baubles-1.12-1.5.2.jar                          | None                                     |
       | LCHIJA | reborncore        | 3.19.5       | RebornCore-1.12.2-3.19.5-universal.jar          | None                                     |
       | LCHIJA | techreborn        | 2.27.3.1084  | TechReborn-1.12.2-2.27.3.1084-universal.jar     | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
       | LCHIJA | thaumcraft        | 6.1.BETA26   | Thaumcraft-1.12.2-6.1.BETA26.jar                | None                                     |
       | LCHIJA | trm               | 1.0          | trm-b2.jar                                      | None                                     |
       | LCHIJA | vanillafix        | 1.0.10-150   | VanillaFix-1.0.10-150.jar                       | None                                     |
       | LCHIJA | techreborn_compat | 1.0.0        | TechReborn-ModCompatibility-1.12.2-1.4.0.76.jar | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  RebornCore: Plugin Engine: 0
              RebornCore Version: 3.19.5
              Runtime Debofucsation 1
              Invalid fingerprint detected for RebornCore!
              RenderEngine: 0
  Suspected Mods: Industrial Magic - TechReborn Crossover (trm)

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

2. This tab bugs when the "/thaumcraft reload" command is used.

3. Content suggestion for the Thaumonomicon entries. Change the category's name and adding entries. The en_us.lang suggestion is right bellow:

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#Creatibe Group
itemGroup.trm=Industrial Magic - TechReborn

#blocks
tile.aergenerator.name=Aer Aspect Generator
tile.aurgenerator.name=Auram Aspect Generator

#items
item.thaumiumdrill.name=Thaumium Drill
item.steelomnitool.name=Steel Omni-Tool
item.thaumadvanceddrill.name=Thaumium Advanced Drill
item.techreborn.thaumbattery.name=Thaumium Battery
item.multimeter.name=MultiMeter

#research

tc.research_category.TRM=Industrial Tech-Magic

research_name.trm:trm=First Step in Magic Tech
research_stage.trm:trm.1=When I was starting my researches about magic, some thoughts about potential uses for magic with technology came across my mind.<BR>This may have some uses but generally, magic and modern science don't fit well together. But, if somehow I could have some benefiths from these experiments, they can lead me to other interesting ideas. Also this is going to help me to understand the limits of both sides and know what NOT to do.
research_stage.trm:trm.2=Okay... I think I can experiment with some things but maybe this won't go that far as I expected. Well then, let's see how much goods I can get from the The Magitech Principle.<BR>That is a not so explored principle which comes with the idea of the perfect merge between both concepts. Maybe I'll try that by other ways. I think I'll work with small experiments here.

research_name.trm:tools=Magic-Tech Tools
research_stage.trm:tools.1=I had to look to some simple machinery to begin and then, to the complex ones used in the industry. I think I know where to start.
research_stage.trm:tools.2=Yes, definitively I have something here. These are some tools I that can work well, but I'll need to infuse magic in some of the materials. Magic metals? It doesn't seem to be a problem to thaumaturgy.

research_name.trm:gen=New Type Generators
research_stage.trm:gen.1=Oh! OK, this seems promessing. Based on my sketches of the internal circuits from those basic tools, I figured out that essentia can go well with generators.<BR>Yes, there're more than one type of generators, so I'm going with the type I think it'll work better with the technology I'm currently working on, but probably essentia can be used in different ways to generate power.<BR>About the essentia, it'll be easier if I use those which flow through and are present in almost everywhere, AER and AURAM.
research_stage.trm:gen.2=Just as I thought. They work pretty well. The real problem is keep producing essentia to feed them in order to generate energy, specially AURAM.<BR>This can be quite agressive to the enviorment and it's generates tons of Flux. I need to be careful and do my best to balance things, otherwise, the whole work won't worth it.<BR>I hope I discover something else and more useful later on. Actually, I think I could get some inspiration from that Auram Aspect Generator. I think it's a good idea to keep it near to my Research Table. It might help in this category in the future.

XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

**Comment by LupusParsec** [comment]
Also, it doesn't make sense being possible to complete "Magic-Tech Tools" and "New Type Generators" even before completing the first research "First Steps". There're craftings using Brass and Thaumium, even Infusion crafting.

I want to recommend to make Auram Aspect Generator to be used as a Research Aid to get theory knowledge of this category if this mod become bigger in the future (note to the last Thaumonomicon entry).

**Comment by Rumaruka** [comment]
Project Abandoned.
I don`t want to continue 
IndustrialMagic TechReborn

**Comment by LupusParsec** [comment]
So, why didn't you make the source code available to the public?

**Comment by Rumaruka** [comment]
I don`t have source after reinstall OS, sorry

**Comment by LupusParsec** [comment]
[IndustrialMagic-TechReborn-Crossover-master.zip](https://github.com/Rumaruka/IndustrialMagic-TechReborn-Crossover/files/9435481/IndustrialMagic-TechReborn-Crossover-master.zip)

Using https://jdec.app/ I maneged to decompile the .class and I tryed to organize the project. Probably some functions and the gradle files may be missing. But do you think this helps as a repo? It's all yours.

**Comment by LupusParsec** [comment]
Oh yeah, I tryed to do some changes in the en_us.lang already.
